permalink: /:categories/:year/:month/:day/:title/

seo:
  keywords:
    - rkoots
    - Rajkumar Venkataraman
    - blog
    - academic talks
    - TechNews
    - portfolio
    - Jekyll
    - personal website
    - data science
    - engineering leadership
    - open source
    - teaching
    - ADF
    - Applied Data Finance
    - fintech
    - cloud engineering
    - microservices
    - API development
    - AWS
    - GCP
    - Java
    - Python
    - Spring Boot
    - MySQL
    - Elasticsearch
    - CI/CD
    - Jenkins
    - Kubernetes
    - DevOps
    - software architecture
    - scalability
    - fraud detection
    - underwriting systems
    - loan management systems
    - big data
    - analytics
    - leadership in tech
    - Director of Engineering

collections:
  blog:
    output: true
    permalink: /blog/:year/:month/:day/:title/