baseurl: "/blog"  # For serving the site at /blog path
url: "https://rkoots.github.io"

title: Rajkumar's Blog
email: rajkumarv88@icloud.com
description: "Techie One is a modern tech blog exploring software engineering, web development, system design, and the latest in technology trends."
twitter_username: rkoots
github_username: rkoots

theme: "minimal-mistakes"
remote_theme: mmistakes/minimal-mistakes
search: true

include:
  - _posts
  - _pages

# Permalink settings for posts
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
