name: News Blog - Generate

on:
  #  push:
  #    branches:
  #      - main
  schedule:
    - cron: '0 1 */3 * *'  # Every 4 hours
  workflow_dispatch:  # Optional: allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          cd ./blog 
          pip install -r requirements.txt

      # Run the Python script with environment variables
      - name: Run tech post generator
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          cd ./blog  
          python generate_blog_post_gemini.py
          

      # Commit and push changes to the repository (if needed)
      - name: Commit and push changes
        run: |
          cd ./blog  
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add _posts/
          git commit -m "Add tool post"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/rkoots/rkoots.github.io.git HEAD:main
